/**
 * Stable, locale-independent identifiers for every user-facing validation
 * and server error in the app. Business logic and Zod schemas return these
 * codes (never translated prose) — `translateErrorCode()` resolves them to
 * localized text at the request/presentation boundary (I18N-1).
 */
export const ERROR_CODE_MESSAGE_KEYS = {
  VALIDATION_NAME_REQUIRED: "validationNameRequired",
  VALIDATION_NAME_TOO_LONG: "validationNameTooLong",
  VALIDATION_EMAIL_INVALID: "validationEmailInvalid",
  VALIDATION_PASSWORD_TOO_SHORT: "validationPasswordTooShort",
  VALIDATION_PASSWORD_TOO_LONG: "validationPasswordTooLong",
  VALIDATION_PASSWORD_REQUIRED: "validationPasswordRequired",
  VALIDATION_CURRENT_PASSWORD_REQUIRED: "validationCurrentPasswordRequired",
  VALIDATION_CONFIRM_PASSWORD_REQUIRED: "validationConfirmPasswordRequired",
  VALIDATION_PASSWORD_MISMATCH: "validationPasswordMismatch",
  VALIDATION_PASSWORD_SAME_AS_CURRENT: "validationPasswordSameAsCurrent",
  VALIDATION_COMMENT_REQUIRED: "validationCommentRequired",
  VALIDATION_COMMENT_EMPTY: "validationCommentEmpty",
  VALIDATION_COMMENT_TOO_LONG: "validationCommentTooLong",
  VALIDATION_TITLE_REQUIRED: "validationTitleRequired",
  VALIDATION_TITLE_TOO_LONG: "validationTitleTooLong",
  VALIDATION_DESCRIPTION_TOO_LONG: "validationDescriptionTooLong",
  VALIDATION_SUBJECT_REQUIRED: "validationSubjectRequired",
  VALIDATION_SUBJECT_TOO_LONG: "validationSubjectTooLong",
  VALIDATION_ACADEMIC_YEAR_REQUIRED: "validationAcademicYearRequired",
  VALIDATION_ACADEMIC_YEAR_TOO_LONG: "validationAcademicYearTooLong",
  VALIDATION_DOCUMENT_TYPE_INVALID: "validationDocumentTypeInvalid",
  VALIDATION_GRADE_REQUIRED: "validationGradeRequired",
  VALIDATION_LESSON_REQUIRED: "validationLessonRequired",
  VALIDATION_REJECTION_REASON_REQUIRED: "validationRejectionReasonRequired",
  VALIDATION_REJECTION_REASON_TOO_LONG: "validationRejectionReasonTooLong",
  VALIDATION_RATING_REQUIRED: "validationRatingRequired",
  VALIDATION_RATING_NOT_INTEGER: "validationRatingNotInteger",
  VALIDATION_RATING_OUT_OF_RANGE: "validationRatingOutOfRange",
  VALIDATION_REPORT_REASON_INVALID: "validationReportReasonInvalid",
  VALIDATION_REPORT_DESCRIPTION_REQUIRED_FOR_OTHER: "validationReportDescriptionRequiredForOther",
  VALIDATION_INVALID_JSON: "validationInvalidJson",
  VALIDATION_MULTIPART_REQUIRED: "validationMultipartRequired",
  VALIDATION_GENERIC: "validationGeneric",
  AUTH_EMAIL_ALREADY_EXISTS: "authEmailAlreadyExists",
  AUTH_ACCOUNT_NOT_FOUND: "authAccountNotFound",
  AUTH_CURRENT_PASSWORD_INCORRECT: "authCurrentPasswordIncorrect",
  AUTH_INVALID_CREDENTIALS: "authInvalidCredentials",
  AUTH_SIGNIN_AFTER_REGISTER_FAILED: "authSigninAfterRegisterFailed",
  UNEXPECTED_ERROR: "unexpectedError",
  UPLOAD_YOUTUBE_URL_INVALID: "uploadYoutubeUrlInvalid",
  UPLOAD_GOOGLE_FORM_URL_INVALID: "uploadGoogleFormUrlInvalid",
  UPLOAD_FILE_REQUIRED: "uploadFileRequired",
  UPLOAD_FILE_TOO_LARGE: "uploadFileTooLarge",
  UPLOAD_UNSUPPORTED_FILE_TYPE: "uploadUnsupportedFileType",
  UPLOAD_FILE_EXTENSION_MISMATCH: "uploadFileExtensionMismatch",
  UPLOAD_FILE_SIGNATURE_MISMATCH: "uploadFileSignatureMismatch",
  UPLOAD_SAVE_FAILED: "uploadSaveFailed",
  UPLOAD_PREVIEW_SAVE_FAILED: "uploadPreviewSaveFailed",
  UPLOAD_DOCUMENT_SAVE_FAILED: "uploadDocumentSaveFailed",
  UPLOAD_POWERPOINT_CONVERSION_FAILED: "uploadPowerpointConversionFailed",
  TAXONOMY_GRADE_NOT_FOUND: "taxonomyGradeNotFound",
  TAXONOMY_SUBJECT_NOT_FOUND: "taxonomySubjectNotFound",
  TAXONOMY_LESSON_NOT_FOUND: "taxonomyLessonNotFound",
  TAXONOMY_SUBJECT_GRADE_MISMATCH: "taxonomySubjectGradeMismatch",
  TAXONOMY_LESSON_SUBJECT_MISMATCH: "taxonomyLessonSubjectMismatch",
  AUTH_REQUIRED: "authRequired",
  ADMIN_REQUIRED: "adminRequired",
  FORBIDDEN_UPLOAD_ROLE: "forbiddenUploadRole",
  FORBIDDEN_CREATE_ROLE: "forbiddenCreateRole",
  DOCUMENT_NOT_FOUND: "documentNotFound",
  COMMENT_NOT_FOUND: "commentNotFound",
  LESSON_NOT_FOUND: "lessonNotFound",
  TEACHER_NOT_FOUND: "teacherNotFound",
  NOTIFICATION_NOT_FOUND: "notificationNotFound",
  FORBIDDEN_SELF_FOLLOW: "forbiddenSelfFollow",
  FORBIDDEN_UPDATE_DOCUMENT: "forbiddenUpdateDocument",
  FORBIDDEN_DELETE_DOCUMENT: "forbiddenDeleteDocument",
  FORBIDDEN_RESUBMIT_DOCUMENT: "forbiddenResubmitDocument",
  FORBIDDEN_EDIT_COMMENT: "forbiddenEditComment",
  FORBIDDEN_DELETE_COMMENT: "forbiddenDeleteComment",
  SIGNIN_REQUIRED_CREATE: "signinRequiredCreate",
  SIGNIN_REQUIRED_UPDATE: "signinRequiredUpdate",
  SIGNIN_REQUIRED_DELETE: "signinRequiredDelete",
  SIGNIN_REQUIRED_DOWNLOAD: "signinRequiredDownload",
  SIGNIN_REQUIRED_UPLOAD: "signinRequiredUpload",
  DOCUMENT_CONFLICT_STALE: "documentConflictStale",
  DOCUMENT_NOT_REJECTED: "documentNotRejected",
  DOCUMENT_NOT_PENDING: "documentNotPending",
  REPORT_ALREADY_SUBMITTED: "reportAlreadySubmitted",
  NO_FILE_AVAILABLE: "noFileAvailable",
  FILE_NOT_AVAILABLE: "fileNotAvailable",
  FILE_NO_LONGER_AVAILABLE: "fileNoLongerAvailable",
  PREVIEW_UNSUPPORTED_FILE_TYPE: "previewUnsupportedFileType",
  SUBJECT_ID_QUERY_REQUIRED: "subjectIdQueryRequired",
  RATE_LIMITED: "rateLimited",
  FAILED_LOAD_GRADES: "failedLoadGrades",
  FAILED_LOAD_SUBJECTS: "failedLoadSubjects",
  FAILED_LOAD_LESSONS: "failedLoadLessons",
  FAILED_LOAD_DOCUMENTS: "failedLoadDocuments",
  FAILED_LOAD_DOCUMENT: "failedLoadDocument",
  FAILED_CREATE_DOCUMENT: "failedCreateDocument",
  FAILED_UPDATE_DOCUMENT: "failedUpdateDocument",
  FAILED_DELETE_DOCUMENT: "failedDeleteDocument",
  FAILED_LOAD_COMMENTS: "failedLoadComments",
  FAILED_SAVE_COMMENT: "failedSaveComment",
  FAILED_UPDATE_COMMENT: "failedUpdateComment",
  FAILED_DELETE_COMMENT: "failedDeleteComment",
  FAILED_SAVE_RATING: "failedSaveRating",
  FAILED_LOAD_RATING_SUMMARY: "failedLoadRatingSummary",
  FAILED_LOAD_SAVED_STATE: "failedLoadSavedState",
  FAILED_SAVE_DOCUMENT: "failedSaveDocument",
  FAILED_REMOVE_SAVED_DOCUMENT: "failedRemoveSavedDocument",
  FAILED_SUBMIT_REPORT: "failedSubmitReport",
  FAILED_LOAD_REPORT_STATUS: "failedLoadReportStatus",
  FAILED_LOAD_PREVIEW: "failedLoadPreview",
  FAILED_DOWNLOAD_DOCUMENT: "failedDownloadDocument",
  FAILED_RESUBMIT_DOCUMENT: "failedResubmitDocument",
  FAILED_LOAD_FOLLOW_STATE: "failedLoadFollowState",
  FAILED_FOLLOW_TEACHER: "failedFollowTeacher",
  FAILED_UNFOLLOW_TEACHER: "failedUnfollowTeacher",
  FAILED_FOLLOW_LESSON: "failedFollowLesson",
  FAILED_UNFOLLOW_LESSON: "failedUnfollowLesson",
  FAILED_LOAD_NOTIFICATIONS: "failedLoadNotifications",
  FAILED_UPDATE_NOTIFICATION: "failedUpdateNotification",
  FAILED_UPDATE_NOTIFICATIONS_ALL: "failedUpdateNotificationsAll",
  FAILED_LOAD_UNREAD_COUNT: "failedLoadUnreadCount",
  FAILED_APPROVE_DOCUMENT: "failedApproveDocument",
  FAILED_REJECT_DOCUMENT: "failedRejectDocument",
  FAILED_REGISTER: "failedRegister",
  FAILED_UPDATE_PROFILE: "failedUpdateProfile",
  FAILED_CHANGE_PASSWORD: "failedChangePassword",
  UNABLE_UPDATE_FOLLOW_STATUS: "unableUpdateFollowStatus",
  UNABLE_SAVE_COMMENT: "unableSaveComment",
  UNABLE_DELETE_COMMENT: "unableDeleteComment",
  UNABLE_LOAD_COMMENTS: "unableLoadComments",
  UNABLE_UPDATE_NOTIFICATIONS: "unableUpdateNotifications",
  UNABLE_SUBMIT_REPORT: "unableSubmitReport",
  UNABLE_UPDATE_SAVED_DOCUMENT: "unableUpdateSavedDocument",
  UNABLE_SAVE_RATING: "unableSaveRating",
} as const satisfies Record<string, string>;

export type ErrorCode = keyof typeof ERROR_CODE_MESSAGE_KEYS;

export function errorMessageKey(code: ErrorCode): (typeof ERROR_CODE_MESSAGE_KEYS)[ErrorCode] {
  return ERROR_CODE_MESSAGE_KEYS[code];
}

export function isErrorCode(value: string): value is ErrorCode {
  return value in ERROR_CODE_MESSAGE_KEYS;
}
